### ISSUE TITLE
Removing "filters"

### ISSUE THREAD

**Issue by JeroenDeDauw** [lingua-libre/QueryViz#2]
Is it possible to remove the "filters" UI element?

![image](https://user-images.githubusercontent.com/146040/117318569-d52abd80-ae8a-11eb-88d4-c0af25d1d81c.png)

For my use case we just want the table.

I looked at the code and my impression is that the answer is "no". It also seems like this extension is not actively developed. Are contributions welcome?

----
EDIT: This extension's html is generated in [/modules/ext.queryViz.QueryViz.js](https://github.com/lingua-libre/QueryViz/blob/master/modules/ext.queryViz.QueryViz.js). Edit is a bit complex. CSS `display:none` at the right place is also an option.

**Comment by hugolpz** [comment]
Hello @JeroenDeDauw, thank for opening this issue. 
Yes, contributions are welcome. I admit I don't understand that Filter's mission. This plugin's developer is in a mission near the Antartic (yes, really ^^), as a sysop for a scientific mission. We are looking for fixes, if you can have fun with it, go ahead. Just ping me when you need something to be done in term of accept a PR or else.

Also, which user are you on LinguaLibre ? ([hi!](https://lingualibre.org/wiki/User:Yug))

**Comment by JeroenDeDauw** [comment]
I am not familiar with LinguaLibre. This ticket was created as part of consulting work I did for the German National Library. They have since moved on to a custom solution and are not using QueryViz.

**Comment by hugolpz** [comment]
Did you work on that solution ? Is it open source ?

**Comment by JeroenDeDauw** [comment]
It is a GND specific solution: https://github.com/ProfessionalWiki/GND

**Comment by hugolpz** [comment]
I see, congratulation for this achievement !
Poslovitch, the current main dev at LinguaLibre, just told me QueryViz was deeply coded as a LinguaLibre specific solution as well. Anyway, it's nice to see this ecosystem growing more dynamic. 🥳

**Comment by hugolpz** [comment]
Moved to https://phabricator.wikimedia.org/T313343
